### GET /r/{id}
GET http://localhost:8080/api/r/{{repo_id}}

### GET /r/search
GET http://localhost:8080/api/r/search

### GET /r/labels
GET http://localhost:8080/api/r/labels?name={{label_name}}&page={{page}}

### GET /r/topics
GET http://localhost:8080/api/r/topics?name={{topic_name}}&page={{page}}

### GET /r/languages
GET http://localhost:8080/api/r/languages

### GET /r/licenses
GET http://localhost:8080/api/r/licenses?name={{license_name}}&page={{page}}

### GET /r/stats
GET http://localhost:8080/api/r/stats
