FROM node:lts-alpine AS build

RUN apk update && apk add moreutils

RUN npm install minify -g

COPY html html/

RUN for file in html/js/*.js; \
    do minify $file | sponge $file; \
    done

FROM nginx:1.25.1-alpine-slim

COPY --from=build html /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
