FROM node:18.15-alpine AS build

RUN apk update && apk add moreutils

RUN npm install minify -g

COPY html html/

RUN for file in html/js/*.js; \
    do minify $file | sponge $file; \
    done

FROM nginx:1.23.3-alpine-slim

COPY --from=build html /usr/share/nginx/html

EXPOSE 3030

COPY docker/fe-entrypoint.sh /
RUN chmod 777 /fe-entrypoint.sh

ENTRYPOINT ["/fe-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
